# Generated by Django 5.2.5 on 2025-08-12 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_Size',
            new_name='ProductSize',
        ),
    ]
